export default [
  {
    id: 1,
    title: 'Join Group Mountain Biking',
    statusbar: 'Join Now',
    coverImage: '/images/Mountain-Bike.png',
    stats: {
      rating: 4.8,
      reviewCount: 33,
    },
    location: 'Canada',
    price: 130,
    openSpots: 10,
  },
  {
    id: 2,
    title: 'Travel the World with us',
    statusbar: 'Join Now',
    coverImage: '/images/travel.jpg',
    stats: {
      rating: 4.9,
      reviewCount: 40,
    },
    location: 'USA',
    price: 400,
    openSpots: 0,
  },
  {
    id: 3,
    title: 'Join for a Group Hike ',
    statusbar: 'Join Now',
    coverImage: '/images/group-hiking.jpg',
    stats: {
      rating: 4.5,
      reviewCount: 25,
    },
    location: 'USA',
    price: 120,
    openSpots: 5,
  },
  {
    id: 4,
    title: 'Explore the Nature with us',
    statusbar: 'Explore',
    coverImage: '/images/Nature.jpg',
    stats: {
      rating: 4.5,
      reviewCount: 20,
    },
    location: 'Austria',
    price: 300,
    openSpots: 5,
  },
  {
    id: 5,
    title: 'Life lessons with Katie Zaferes',
    statusbar: 'ONLINE',
    coverImage: '/images/image.png',
    stats: {
      rating: 5.0,
      reviewCount: 20,
    },
    location: 'Online',
    price: 135,
    openSpots: 0,
  },
  {
    id: 6,
    title: 'Wedding photography ',
    statusbar: 'ONLINE',
    coverImage: '/images/wedding-photography.png',
    stats: {
      rating: 4.0,
      reviewCount: 35,
    },
    location: 'Online',
    price: 125,
    openSpots: 10,
  },
];
